version: 2.1
jobs:
  build-recipe-app-step:
    docker:
    - image: circleci/openjdk:11-browsers-legacy

    working_directory: ~/Learning-Spring5/recipe-app

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout:
        path: ~/Learning-Spring5

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn install -DskipTests

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

    - run: mvn integration-test

    - store_test_results:
        path: target/surefire-reports

    - run:
        name: Send to CodeCov
        command: bash <(curl -s https://codecov.io/bash)
