version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11

    working_directory: ~/Learning-Spring5/PetClinic`

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout:
        path: ~/Learning-Spring5

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "PetClinic/pom.xml" }}
        - v1-dependencies-

    - run: mvn install -DskipTests

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "PetClinic/pom.xml" }}

    - run: cd PetClinic && mvn integration-test
